name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Releases to Docker
      # so far only on releases
      uses: elgohr/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/')
      with:
        name: pytorchlightning/pytorch_lightning
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
